asp.net/myproject2/WebApplication1/Controllers/DateController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class DateController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Time()
        {
            return Content (DateTime.Now.ToString());
        }
    }
}

asp.net/myproject2/WebApplication1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductContext _context;
        public ProductController(ProductContext context) 
        { 
            _context = context;
        }

        public IActionResult Index( string name)
        {
            ViewBag.name  = name;
            var data = _context.Prodects.ToList();
            var file1 = _context.Files.ToList();
            for (int i = 0; i < data.Count; i++)
            {
                for (int j = 0; j < file1.Count; j++)
                {
                    if (data[i].FileId == file1[j].Id)
                    {
                        data[i].FileId = file1[j].Name;
                    }
                }
            }
            return View(data);
        }

        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                //取得使用者上傳檔案的原始檔名
                var fileOriginName = Path.GetFileName(productViewModel.File.FileName);
                //取原始檔名中的副檔名
                var fileExt = Path.GetExtension(fileOriginName);
                //為避免使用者上傳的檔案名稱發生重複，重新給一個亂數名稱
                var fileNewName = Path.GetRandomFileName();
                //指定要寫入的路徑、檔名和副檔名
                var filePath = "C:/Users/abc04/Desktop/asp.net/myproject2/WebApplication1/wwwroot/lib/data/" + fileNewName + fileExt;

                //將使用者上傳的檔案寫入到指定路徑
                await using (var stream = System.IO.File.Create(filePath))
                {
                    //執行寫入
                    await productViewModel.File.CopyToAsync(stream);
                }
                var file = new Models.File()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = fileNewName + fileExt
                };

                var last = _context.Prodects.OrderByDescending(d => d.Id).FirstOrDefault();
                if (last == null)
                {
                    var product = new Prodect()
                    {
                        Id = 1,
                        Name = productViewModel.Name,
                        Price = productViewModel.Price,
                        FileId = file.Id
                    };
                    _context.Prodects.Add(product);
                }
                else 
                {
                    var product = new Prodect()
                    {
                        Id = last.Id + 1,
                        Name = productViewModel.Name,
                        Price = productViewModel.Price,
                        FileId = file.Id
                    };
                    _context.Prodects.Add(product);
                }
                _context.Files.Add(file);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(productViewModel);
        }

        /*public IActionResult AddProduct(Prodect product)//新增功能
        {
        if (ModelState.IsValid)//ModelState.IsValid會因為空值(id等等)或不符合規則改為false
        { 
        var last = _context.Prodects.OrderByDescending(d => d.Id).FirstOrDefault();
        product.Id = last.Id + 1;
        _context.Prodects.Add(product);
        _context.SaveChanges();
        return RedirectToAction("Index");
        }
        return View(product);
        }*/
        [HttpGet]
        public IActionResult DeleteProduct(int ID)//刪除功能確認刪除案件
        {
            var data = _context.Prodects.FirstOrDefault(d => d.Id == ID);
            return View(data);
        }

        [HttpPost]
        public IActionResult TODeleteProduct(int ID)//回傳回來執行刪除功能
        {
            var data = _context.Prodects.FirstOrDefault(d => d.Id == ID);

            if (data != null)
            { 
                _context.Prodects.Remove(data);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult GetProduct(int ID)//產品細節
        {
            var data = _context.Prodects.FirstOrDefault(d => d.Id == ID);
            return View(data);
        }
       
        public IActionResult UpdateProduct(int ID)//案修改後跑來得Action
        {
            var data = _context.Prodects.FirstOrDefault(d => d.Id == ID);
            return View(data);
        }
        [HttpPost]
        public IActionResult UpdateProduct(Prodect product)//(int ID,string Name,decimal Price) 從UpdateProduct頁面 HttpPost回傳回來
        {
            var data = _context.Prodects.FirstOrDefault(d => d.Id == product.Id);

            if (data != null) 
            { 
                data.Name = product.Name;
                data.Price = product.Price;
                _context.SaveChanges();
            }


            return RedirectToAction("Index");
        }
    }
}

asp.net/myproject2/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Date" asp-action="Index">Date</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

asp.net/myproject2/WebApplication1/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid ">  
            <a class="navbar-brand " href="#">首頁</a>
            <a class="navbar-brand NavigationBar-actionMenu-button " asp-area="" asp-controller="Home" asp-action="Index" data-bs-toggle="modal" data-bs-target="#exampleModal">會員登入</a>
            <a class="navbar-brand justify-content-end flex-grow-1 pe-3" asp-area="" asp-controller="Product" asp-action="Index">產品</a>
            <a class="navbar-brand">@ViewBag.name</a>
            <button class="navbar-toggler " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasCart" aria-controls="offcanvasCart" aria-label="Toggle navigation">
                <img src="~/lib/data/cart.svg" style="width:0.8cm;height:0.8cm;"/>
                <span class="badge badge-pill badge-danger">1</span>
            </button>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @**購物車彈跳視窗*@
            <div class="offcanvas offcanvas-end   bg-white navbar-brand" tabindex="-1" id="offcanvasCart" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel" style="color:black">購物車</h5>
                    <button type="button" class="btn-close " data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <img src="~/lib/data/aespa.jpg" class="img-thumbnail"/>
                <div id="cart" style="color:black"></div>
                <ul class="nav">
                    <li class="nav-item">
                        <a class="btn btn-primary" >結帳</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" id="cancel">取消</a>
                    </li>
                </ul>
            </div>
            @*三條線的彈跳視窗*@
            <div class="offcanvas offcanvas-end   bg-dark navbar-brand" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex mt-3" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    @*會員登入*@
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" asp-controller="Home" asp-action="Login">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">會員登入</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body form-group">
                        <label>帳號</label>
                        <input type="text" name="Account" class="form-control" />
                        <br />
                        <label>密碼</label>
                        <input type="text" name="Password" class="form-control" />
                        <br />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">登入</button>
                        <input type="button" class="btn btn-secondary" value="註冊" onclick="location.href='@Url.Action("AddMember", "Home")'" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    @*幻燈片輪播*@
    <div id="carouselExampleIndicators" class="carousel slide bg-dark">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/lib/data/LE.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/lib/data/NMIXX.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/lib/data/IVE.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/lib/data/Twice.jpg" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev " type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next " type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js">
    </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
        <script>
            var cart = [];
            $(document).ready(function(){
                function setCart(){
                    var cartList = "";
                    var cartnum = 0 ;
                    if (localStorage.getItem("cart")) 
                    {
                        cart = JSON.parse(localStorage.getItem("cart"));
                    }
                    
                    for (let i = 0; i < cart.length; i++) 
                    {
                        cartList += 
                        '<div class="card w-50">'+ 
                        '<div class="card-body">'+
                        '<h5 class="card-title">'+cart[i]["name"]+'</h5>'+
                        '<p class="card-text">'+cart[i]["price"]+'*'+cart[i]["amount"]+'</p>'+
                        '</div>'+ 
                        '</div>';
                        cartnum += Number(cart[i]["amount"]);
                    }
                    $('.badge').html(cartnum);
                    $("#cart").empty().append(cartList);
                }
                setCart();
                $('.add_cart').click(function () {
                    let product = $(this).closest(".card-body");
                    let True = 0;
                    if (localStorage.getItem("cart")) 
                    {
                        cart = JSON.parse(localStorage.getItem("cart"));
                        for(let i = 0 ;i < cart.length;i++ )
                        {
                            if (cart[i]["name"] == product.find(".card-title").text())
                            {
                                cart[i]["amount"] = (Number(cart[i]["amount"])+1).toString();
                                cart.push();
                                localStorage.setItem("cart", JSON.stringify(cart));
                                True = 1;
                            }
                        }
                    }
                    if(True == 0)/*判斷是不是新的項目*/ 
                    {
                        let newitem = {
                        name: product.find(".card-title").text(),
                        price: $(this).data("price"),
                        amount: "1",
                        };
                        cart.push(newitem);
                        localStorage.setItem("cart", JSON.stringify(cart));
                        True = 0;
                    }
                    setCart();
                });
                $("#cancel").click(function(){
                    cart = [];
                    localStorage.removeItem("cart");
                    setCart();
                });
            });

            
        </script>
</body>
</html>

asp.net/myproject2/WebApplication1/Views/Shared/_Layout2.cshtml.cshtml
@page
@model WebApplication1.Views.Shared._Layout2.cshtmlModel
@{
}

asp.net/myproject2/WebApplication1/Views/Shared/_ProductListPartial.cshtml
@model  List<Prodect>;

@foreach (var p in Model)
{
    <div>
        <img src="~/lib/data/@p.FileId" width="100" height="100" /><br />
        <a class="" asp-area="" asp-controller="Product" asp-action="GetProduct" asp-route-id="@p.Id">@($"{p.Id} - {p.Name} - {p.Price}")</a>
        <br/>
        <a class="btn btn-primary" asp-area="" asp-controller="Product" asp-action="UpdateProduct" asp-route-id="@p.Id">修改</a>
        <a class="btn btn-primary" asp-area="" asp-controller="Product" asp-action="DeleteProduct" asp-route-id="@p.Id">刪除</a>
    </div>
}